services:
  web:
    build: .
    container_name: gin_app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=app_db
      - DB_PORT=5432

  db:
    image: postgres:14.16-alpine3.20
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "app_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
